dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.10
  chewie: ^1.2.2
  http: ^0.13.3
  flutter_mpesa: ^0.0.2  # Add this for MPesa integration
  dio: ^4.0.0  # Add this for API management